e-commerceMVC/e-commerceMVC/Controllers/StoreController.cs
using e_commerceMVC.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerceMVC.Controllers
{
    public class StoreController : Controller
    {

        StoreContext db = new StoreContext();
        
        
        //
        // GET: /Store/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {

            var product = db.Products.Find(id);


            return View(product);
        }

        public ActionResult List(string kategoryname)
        {
            var kategory = db.Kategories.Include("Products").Where(g => g.Name.ToUpper() == kategoryname.ToUpper()).Single();
            var products = kategory.Products.ToList();

            return View(products);
        }

        [ChildActionOnly]
        public ActionResult KategoriesMenu() 
        {

            var kategories = db.Kategories.ToList();


            return PartialView("_KategoriesMenu",kategories);
        }



        public ActionResult ProductSuggestions(string term) 
        {
            var products = this.db.Products.Where(a => !a.IsHidden && a.ProductName.ToLower().Contains(term.ToLower()))
                .Take(5).Select(a => new { label = a.ProductName });

            return Json(products, JsonRequestBehavior.AllowGet);
        }



	}
}

e-commerceMVC/e-commerceMVC/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace e_commerceMVC.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

e-commerceMVC/e-commerceMVC/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

e-commerceMVC/e-commerceMVC/Views/Shared/_ManageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="description" content="Zarządzanie sklepu internetowego CPU Tech" />
    <meta name="keywords" content="notebook, PC, karta graficzna, komputer, procesor, CPU" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" />

    <style>
        .manageLink {
            height: 42px;
            float: left;
            line-height: 40px;
            font-size: 14px;
            padding-left: 40px;
            /*background-color: #585858;*/
            background-color: #39312E;
            color: white;
        }

        a.manageLink, a.manageLink:hover, a.manageLink:visited {
            color: white;
        }
    </style>

</head>
<body>
    <header>
        <div style="overflow: hidden; margin-bottom: 30px;">

            <a class="manageLink" href="@Url.Action("Index", "Home")">
                Start
            </a>
            <a class="manageLink" href="@Url.Action("Index", "Manage")">
                Twoje dane
            </a>
            @if (@User.IsInRole("Admin"))
            {
                <a class="manageLink" href="@Url.Action("AddProduct", "Manage")">
                    Dodaj
                </a>
                <a class="manageLink" href="@Url.Content("~/hangfire")">
                    Jobs
                </a>
                <a class="manageLink" href="@Url.Content("~/elmah")">
                    Logi
                </a>
            }
            <a class="manageLink" href="@Url.Action("OrdersList", "Manage")" style="width: 100px">
                Zamówienia
            </a>

            <a id="cart-header-link" href="@Url.Action("Index", "Cart")">
                KOSZYK (<span id="cart-header-items-count">@Html.Action("GetCartItemsCount", "Cart")</span>)
                <span id="cart-header-logo"></span>
            </a>

            @Html.Partial("_LoginPartial")

        </div>

        <div id="breadcrumb-section">
            <img src="@Url.Content("~/Content/Images/home-small.png")" />
            @Html.MvcSiteMap().SiteMapPath()
        </div>

    </header>

    <div>
        @RenderBody()
    </div>

    <footer>
        <nav>
            <ul>
                <li><a href="">O nas</a></li>
                <li><a href="">Kontakt</a></li>
                <li><a href="">Wysyłka</a></li>
                <li><a href="">Regulamin</a></li>
            </ul>
        </nav>
        <div id="footer-cd-logo">
            <img src="@Url.Content("~/Content/images/footer-cd.png")" />
        </div>

        <div id="footer-copyright">
            Copyright &copy; 2016 Online
        </div>
    </footer>

    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

e-commerceMVC/e-commerceMVC/Views/Shared/_RightSectionLayout.cshtml
@{
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<div id="productlist-content">

    @Html.Action("KategoriesMenu","Store")

    <div id="productlist-rightsection">
        <div id="breadcrumb-section">
            <img src="../Content/Images/home-small.png" />
            @Html.MvcSiteMap().SiteMapPath()
        </div>
        <section class="content-section">
            <div class="section-header" style="margin-bottom:0px;">
                <h1>
                    @RenderSection("SectionTitle", required: false)
                </h1>
            </div>
            @RenderBody()
        </section>
    </div>
</div>

@section ScriptsBottom
    {
        @RenderSection("ScriptsBottom", required: false)
    }

e-commerceMVC/e-commerceMVC/Views/Shared/_StoreLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta name="description" content="Strona główna sklepu internetowego CPU Tech" />
    <meta name="keywords" content="notebook, PC, karta graficzna, komputer, procesor, CPU" />
    <meta name="language" content="pl" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />

    @System.Web.Optimization.Styles.Render("~/Content/themes/base/css")


</head>
<body>
    <header>
        <div style="overflow:hidden;">
            <a id="facebook-header" href="">
                Dołacz do 1500 fanów na FB
            </a>
            <a id="cart-header-link" href="">
                KOSZYK (@Html.Action("GetCartItemsCount","Cart"))
                <span></span>
            </a>

            @Html.Partial("_LoginPartial")

        </div>
        <a id="main-header-logo" href="@Url.Content("~/")">
            <img src="../Content/Images/logo3.png" class="center" />
        </a>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer>
        <nav>
            <ul>
                <li>
                    @Html.ActionLink("O nas", "StaticContent", "Home", new { viewname = "onas" }, null)
                </li>
                <li>
                    @Html.ActionLink("Kontakt", "StaticContent", "Home", new { viewname = "kontakt" }, null)
                </li>
                <li>
                    @Html.ActionLink("Wysyłka", "StaticContent", "Home", new { viewname = "wysylka" }, null)
                </li>
                <li>
                    @Html.ActionLink("Regulamin", "StaticContent", "Home", new { viewname = "regulamin" }, null)
                </li>
            </ul>
        </nav>

        <div id="footer-copyright">
            Copyright &copy; 2016 Online
        </div>
    </footer>
    @RenderSection("ScriptsBottom", required: false)
</body>
</html>

e-commerceMVC/e-commerceMVC/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Wyświetlana strona mobilna
            @Html.ActionLink("przełącz", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Wyświetlana strona klasyczna
            @Html.ActionLink("przełącz", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}